name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          wget -qO- https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.zip | bsdtar -xvf-
          ./allure-2.20.0/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
